
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    networks:
      - app-nest


networks:
  app-nest:
    driver: bridge
