
services:
  nest.order-svc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    env_file:
      - .env
#    depends_on:
#      - nest.order-svc.postgres
    networks:
      - app-nest

#  nest.order-svc.postgres:
#    image: postgres:15
#    restart: always
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5434:5432"
#    volumes:
#      - pgdata-nest:/var/lib/postgresql/data
#    networks:
#      - app-nest
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#
#  nest.order-svc.pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#    ports:
#      - "9000:80"
#    depends_on:
#      - nest.order-svc.postgres
#    networks:
#      - app-nest


#volumes:
#  pgdata-nest:

networks:
  app-nest:
    driver: bridge
