
services:
  nest.payment-svc:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nest.payment-svc.rabbitmq
    ports:
      - "8030:8030"
    networks:
      - app-nest

  nest.payment-svc.rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # порт AMQP
      - "15672:15672" # порт UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-nest
networks:
  app-nest:
    driver: bridge
